# Generated by Django 2.2.7 on 2019-11-22 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import report_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_as_string', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_peer_review', models.TextField(blank=True, max_length=100000)),
                ('title_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('executive_summary', models.TextField(blank=True, max_length=100000)),
                ('executive_summary_peer_review', models.TextField(blank=True, max_length=100000)),
                ('executive_summary_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('introduction', models.TextField(blank=True, max_length=100000)),
                ('introduction_peer_review', models.TextField(blank=True, max_length=100000)),
                ('introduction_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('body', models.TextField(blank=True, max_length=100000)),
                ('body_peer_review', models.TextField(blank=True, max_length=100000)),
                ('body_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('conclusion', models.TextField(blank=True, max_length=100000)),
                ('conclusion_peer_review', models.TextField(blank=True, max_length=100000)),
                ('conclusion_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('recommendations', models.TextField(blank=True, max_length=100000)),
                ('recommendations_peer_review', models.TextField(blank=True, max_length=100000)),
                ('recommendations_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('references', models.TextField(blank=True, max_length=100000)),
                ('references_peer_review', models.TextField(blank=True, max_length=100000)),
                ('references_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('tags_as_string', models.TextField(blank=True, max_length=1000)),
                ('tags_peer_review', models.TextField(blank=True, max_length=1000)),
                ('tags_peer_review_response', models.TextField(blank=True, max_length=100000)),
                ('reviewer_as_string', models.CharField(blank=True, max_length=300)),
                ('basic_report_id_number', models.CharField(default=report_admin.models.number, editable=False, max_length=10)),
                ('basic_report_id_year', models.PositiveIntegerField(default=report_admin.models.current_year, editable=False)),
                ('version', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('update_comment', models.TextField(blank=True, max_length=5000)),
                ('update', models.BooleanField(blank=True, default=False)),
                ('typo_update', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('edited_in_admin_by', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(on_delete=models.SET(report_admin.models.get_sentinel_user), related_name='author', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=models.SET(report_admin.models.get_sentinel_user), related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='status.Status')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='tags.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='BasicReportVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('basic_report_author_as_string', models.CharField(blank=True, max_length=250)),
                ('basic_report_reviewer_as_string', models.CharField(blank=True, max_length=250)),
                ('basic_report_title', models.CharField(blank=True, max_length=250)),
                ('basic_report_title_peer_review', models.TextField(blank=True, max_length=1000)),
                ('basic_report_title_peer_review_response', models.TextField(blank=True, max_length=1000)),
                ('basic_report_executive_summary', models.TextField(blank=True, max_length=5000, null=True)),
                ('basic_report_executive_summary_peer_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_executive_summary_peer_review_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_introduction', models.TextField(blank=True, max_length=5000, null=True)),
                ('basic_report_introduction_peer_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_introduction_peer_review_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_body', models.TextField(blank=True, max_length=5000, null=True)),
                ('basic_report_body_peer_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_body_peer_review_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_conclusion', models.TextField(blank=True, max_length=5000, null=True)),
                ('basic_report_conclusion_peer_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_conclusion_peer_review_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_recommendations', models.TextField(blank=True, max_length=5000, null=True)),
                ('basic_report_recommendations_peer_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_recommendations_peer_review_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_references', models.TextField(blank=True, max_length=5000, null=True)),
                ('basic_report_references_peer_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_references_peer_review_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_tags_as_string', models.TextField(blank=True, max_length=5000, null=True)),
                ('basic_report_tags_peer_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report_tags_peer_review_response', models.TextField(blank=True, max_length=1000, null=True)),
                ('basic_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_admin.BasicReport')),
            ],
        ),
    ]
