# Generated by Django 2.2.7 on 2019-12-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicreport',
            name='version',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
