# Generated by Django 2.2.7 on 2019-12-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0003_basicreport_eb_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicreport',
            old_name='eb_slug',
            new_name='slug',
        ),
    ]
