# Generated by Django 2.2.7 on 2019-12-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0005_auto_20191205_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicreportversion',
            name='basic_report_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='basicreportversion',
            name='basic_report_title_peer_review',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='basicreportversion',
            name='basic_report_title_peer_review_response',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
