# Generated by Django 2.2.7 on 2019-12-06 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0006_auto_20191205_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicreport',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='basicreportversion',
            name='basic_report_unique_id',
            field=models.UUIDField(default=7520934750293485723, editable=False),
            preserve_default=False,
        ),
    ]
