# Generated by Django 2.2.7 on 2019-12-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0007_auto_20191206_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicreport',
            name='update_comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
