# Generated by Django 2.2.7 on 2019-12-14 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0008_auto_20191206_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicreportversion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
