# Generated by Django 2.2.7 on 2019-12-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0009_basicreportversion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicreport',
            old_name='basic_report_id_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='basicreport',
            old_name='basic_report_id_year',
            new_name='id_year',
        ),
    ]
