# Generated by Django 2.2.7 on 2019-12-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_admin', '0012_auto_20191218_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicreport',
            name='cancel_recall',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
